comigo/config/routes.rb
Rails.application.routes.draw do
  get 'monitor/index'

  get 'dashboard/index'

  get 'dashboard/account'

  get 'dashboard/billing'

  get 'dashboard/help'

  get 'dashboard/myproducts'

  get 'cosmo/index'

  get 'panel/index'

  get 'home/index', :as=> :home_index
  
  get 'home/pricing'

  get 'home/about'

  get 'home/contact'

  get "home/privacy_policy"
  
  get "panel/manageusers"
  get "panel/manageproducts", :as => :dashboard_manage_products
  get "panel/account", :as => :dashboard_manage_account
  get "panel/billing"
  get "panel/help"
  
  get "panel/trainai/:nickname", to: "panel#trainai"
  get '/panel/trainai', to: redirect('/panel/trainai/all')

  get '/panel',  to: 'panel#index'
  get "/dashboard", to: "dashboard#index"
  
  get "/cosmo", to: "cosmo#index"
  get "cosmo/facebook"
  get "cosmo/twitter"
  get "cosmo/instagram"
  

  root 'home#index'
  
  post "panel/add_product_to_user", :as => :add_product_to_user
  
 

  post "panel/manage_notifications", :as => :manage_notifications

  get "human_interactions/destroy/:id" => "human_interactions#destroy", :as => :destroy_interaction
  post "human_interactions/update/:id" => "human_interactions#update", :as => :update_interaction

  devise_for :user, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations',
    omniauth_callbacks: "omniauth_callbacks"
  }
  
  resource :user

  devise_scope :user do
    get '/login', to: 'user/sessions#new'
  end
  
  devise_scope :user do
    get '/signup', to: 'user/registrations#new'
  end

  devise_scope :user do
    get "/logout" => "user/sessions#destroy", :as => :quit_session
  end

  devise_scope :user do
    post "/user/create" => "user/registrations#create", :as=> :create_user_path
  end

  devise_scope :user do
    post "/user/update_profile" => "user/registrations#update_profile", :as=> :manage_user_profile
  end

  devise_scope :user do
     post "/user/update_social_accounts" => "user/registrations#manage_sn_accounts" , :as => :manage_sn_accounts
  end

  devise_scope :user do
    post "/user/password/update" => "user/passwords#update", :as=> :manage_account
  end

  get "/panel/manageusers", :as => :dashboard_manage_users
  

end

comigo/app/controllers/panel_controller.rb
class PanelController < ApplicationController
  
  before_filter :authenticate_user!
  before_filter :is_admin?  
  
  def index
  end

  def account
    user_id = User.where(nickname: current_user.nickname).pluck(:id)[0]
    @user = User.find(user_id)
  end

  def billing
  end

  def help
  end

  def myproducts
  end

  """
  Admin Pages
    db.users.update({'nickname':  'felipeguerrads'  }, {'$set': {'is_admin': true}})

    db.users.update({'nickname':  'felipeguerrads'  }, {'$set': {'tw_user_id': ""}})
    db.users.update({'nickname':  'felipeguerrads'  }, {'$set': {'fb_page_id': ""}})
  """
  #GET 
  def manageproducts
    @products = ["Cosmo"]
    @user_emails = User.all.pluck(:email)
  end
  
  #GET
  def manageusers
    @users = User.all
  end

  def trainai
    @users = User.where(is_admin: false)
    @human_interactions = HumanInteraction.all
    @human_interactions_validated = HumanInteraction.where(already_validated: true)
    @human_interactions_validated_count = HumanInteraction.where(already_validated: true).count
    if params[:nickname].to_s == "all"   
      @human_interactions_facebook = HumanInteraction.where(social_network: "facebook").limit(100)
      @human_interactions_twitter = HumanInteraction.where(social_network: "twitter").limit(100)
    else
      @human_interactions_facebook = HumanInteraction.where(social_network: "facebook", user_nickname: params[:nickname]).limit(100)
      @human_interactions_twitter = HumanInteraction.where(social_network: "twitter", user_nickname: params[:nickname]).limit(100)
    end
  end
  
  #POST
  def add_product_to_user
    user_id = User.where(email: params[:manageproduct][:user_email]).pluck(:id)[0]
    user_object = User.find(user_id)
    user_object.push(products: params[:manageproduct][:product_name])
    flash[:notice] = "Successfully added product to a user"
    redirect_to dashboard_manage_products_path
  end

  def manage_notifications
  end


  def is_admin?
  	if !current_user.is_admin?
  	    redirect_to home_index_path    
  	end
  end

end

comigo/app/helpers/panel_helper.rb
module PanelHelper

	def filter_not_validated(human_interactions)
       not_validated = []
       for h in human_interactions
          if h.already_validated == false
          	not_validated << h
          end
       end
       return not_validated
	end

	def number_of_validated_comments(user_nickname)
		return HumanInteraction.where(user_nickname: user_nickname, admin_nickname: current_user.nickname, social_network: "facebook", already_validated: true).count
	end
    
    def total_number_of_comments(user_nickname)
    	return HumanInteraction.where(user_nickname: user_nickname, social_network: "facebook").count
    end

	def number_of_validated_retweets(user_nickname)
       return HumanInteraction.where(user_nickname: user_nickname, admin_nickname: current_user.nickname, social_network: "twitter", already_validated: true).count
	end
    
  def total_number_of_retweets(user_nickname)
    return HumanInteraction.where(user_nickname: user_nickname, social_network: "twitter").count
  end

  def filter_not_empty_users(users, social_network)
    not_empty_users = []
    for u in users
      human_interactions = HumanInteraction.where(user_nickname: u.nickname, social_network: social_network, already_validated: false)
      if !human_interactions.blank?
         not_empty_users << u
      end
    end
    return not_empty_users
  end

end

comigo/app/views/panel/_humaninteractionfacebook.html.erb
<tr>
	<td id="fb-<%= h.user_nickname%>">
		<b><%= h.user_nickname%></b>
	</td>
	
	<td><%= h.comment_text%></td>
					   	   			
	<td>
		<% if h.reaction_type =="positive"%>
			<span class="label label-success"><%= h.reaction_type%></span>
		
		<%elsif h.reaction_type == "negative"%>
			<span class="label label-danger"><%= h.reaction_type%></span>
		
		<% else %>
			<span class="label label-default">Neutral</span>
		<% end %>
	</td>
					   	   			
	<td class="text-center">
		<div>
			<button data-toggle="modal" data-target="#myModal-<%=h._id%>" class="btn btn-success" type="button" aria-haspopup="true" aria-expanded="true">
										    Feedback
			</button>
		</div>

		<!-- Modal -->
		<div class="modal fade" id="myModal-<%=h._id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						
						<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
							<h4 class="modal-title" id="myModalLabel">Feedback</h4>
					</div>
					
					<div class="modal-body">
						<%= simple_form_for :update, { url: update_interaction_path(h.id) } do |f| %>
							<p><%= h.comment_text%></p>

							<p>
								<label>Which reaction would you classify this comment?</label>
							</p>
							
							<p>
								<%= f.input :suggested_category, :label=>false, :class=>"form-control", collection: ["Positive", "Negative", "Neutral", "Job's Proposal", "Danger", "Spam", "Recomendation"], include_blank: false %>
							</p>

							<p class="text-center">
								<%= f.submit "Send", :class=> "btn btn-primary"%>
							</p>
						<% end %>
					</div>
				</div>
			</div>
		</div>
			<p>
			<%= link_to "Destroy", destroy_interaction_path(:id => h._id), :remote => true, :class=> "btn btn-danger" %>
			</p>
	</td>

</tr>

comigo/app/views/panel/_humaninteractiontwitter.html.erb
 
					   	  
<tr>
	<td id="tw-<%= h.user_nickname%>">
		<b>
			<%= h.user_nickname%>
		</b>
	</td>
					   	   			
	<td>
		<%= h.comment_text%>
	</td>
					   	   			
	<td>
		<% if h.reaction_type =="positive"%>
			<span class="label label-success">
				<%= h.reaction_type%>
			</span>
		<%elsif h.reaction_type =="negative"%>
			<span class="label label-danger">
				<%= h.reaction_type%>
			</span>
		<% else %>
			<span class="label label-default">
				<%= h.reaction_type%>
			</span>
		<% end %>
	</td>
					   	   			
	<td class="text-center">
		<div>
			<button data-toggle="modal" data-target="#myModal-<%=h._id%>" class="btn btn-success" type="button" aria-haspopup="true" aria-expanded="true">
				Feedback
				</button>
		</div>
							
		<!-- Modal -->
		<div class="modal fade" id="myModal-<%=h._id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
					
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="myModalLabel">Feedback</h4>
				</div>
				
				<div class="modal-body">
					<%= simple_form_for :update, { url: update_interaction_path(h.id) } do |f| %>
													
						<p><%= h.comment_text%></p>
						
						<p>
							<label>
								Which reaction would you classify this comment?
							</label>
						</p>
						
						<p>
						<%= f.input :suggested_category, :label=>false, :class=>"form-control", collection: ["Positive", "Negative", "Neutral", "Job's Proposal", "Danger", "Spam", "Recomendation"], include_blank: false %>
						</p>

						<p class="text-center">
							<%= f.submit "Send", :class=> "btn btn-primary"%>
						</p>
					<% end %>
				</div>
			</div>
		</div>
	</div>

	<p>
		<%= link_to "Destroy", destroy_interaction_path(:id => h._id), :remote => true, :class => "btn btn-danger" %>
	</p>

	</td>
</tr>
				

comigo/app/views/panel/_menu.html.erb
<div class="row">
	<div class="text-center">
     		<h5><%= current_user.fullname%> </h5>
     		<span class="label label-success">Admin</span>
	</div>
</div>

<ul class="nav nav-pills nav-stacked text-center">
	<li>
	  	<a href="/panel">Index</a>
	</li>
	
	<li>
		<a href="/panel/trainai/all">Train AI</a>
	</li>

	<li>
	    <a href="/panel/manageproducts">Manage products</a>
	</li>

	<li>
	    <a href="/panel/manageusers">Manage users</a>
	</li>

	<li>
	    <a href="/panel/account">Account</a>
	</li>
</ul>

comigo/app/views/panel/account.html.erb
<div class="row" style="margin-top:30px;">
	
	<div class="col-md-2 well" style="margin-top:30px;">
		<%= render "menu"%>
	</div>	
	
	<div class="col-md-10" style="margin-top:30px;">
		<h1>Account</h1>
		<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
		  <div class="panel panel-default">
		    <div class="panel-heading" role="tab" id="headingOne">
		      <h4 class="panel-title">
		        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
		          Social Networks
		        </a>
		      </h4>
		    </div>
		    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
		      <div class="panel-body ">
		     		<small>
		     			Leave blank what you don't want to change
		     		</small>

					<%= simple_form_for :manage_sn_accounts, { url: manage_sn_accounts_path } do |f| %>
		     		<h2>Facebook</h2>
  					<p>
  						<label>Page link</label>
  					</p>

  					<p>
  						Follow this pattern: <mark>htttp://www.facebook.com/your_user_name</mark>(e.g htttp://www.facebook.com/felipeguerrabr). To figure out your username, see <a href="#">how to figure out my facebook username</a>.
  					</p>
  					
  					<p>
  						<%= f.input :fb_page_link, :label=> false, :class=>"form-control", :placeholder=>  @user.fb_page_link%>
  					</p>

		     		<h2>Twitter</h2>
		     		<p>
  						<label>Twitter username</label>
  					</p>
  					<p>
  						<%= f.input :tw_username, :label=> false, :class=>"form-control", :placeholder=>  "@" + @user.tw_scr_name%>
  					</p>

  					<p class="text-center">
  						<%= f.button :submit, "Update", :class=>"btn btn-primary" %>
  					</p>
  					<% end %>

		     	
		      </div>
		    </div>
		  </div>
		  <div class="panel panel-default">
		    <div class="panel-heading" role="tab" id="headingTwo">
		      <h4 class="panel-title">
		        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
		          Profile
		        </a>
		      </h4>
		    </div>
		    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
		      <div class="panel-body">
		      		
 				<%= simple_form_for :profile, { url: manage_user_profile_path } do |f| %>
		     		<h2>Profile</h2>
  					
  					<p>
  						<label>Your Full Name</label>
  					</p>
  					
  					<p>
  						<%= f.input :name, :label=> false, :class=>"form-control", :placeholder=>  @user.fullname%>
  					</p>

  					<p>
  						<label>Primary used language</label>
  					</p>
  					
  					<p>
  						This basic tell us the language which you most use on your posts or tweets.
  					</p>

  					<p>
  						<%= f.input :language, :label=> false, :class=>"form-control", :placeholder=> @user.language%>
  					</p>

  					<p>
  						<label>Your Country</label>
  					</p>

  					<p>
  						<%= f.input :country, :label=> false, :class=>"form-control", :placeholder=>  @user.country%>
  					</p>

		     		<p>
  						<label>E-mail</label>
  					</p>
  					<p>
  						<%= f.input :email, :label=> false, :class=>"form-control", :placeholder=> @user.email%>
  					</p>

  					<p class="text-center">
  						<%= f.button :submit, "Update", :class=>"btn btn-primary" %>
  					</p>
  					<% end %>


		      </div>
		    </div>
		  </div>
		  <div class="panel panel-default">
		    <div class="panel-heading" role="tab" id="headingThree">
		      <h4 class="panel-title">
		        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
		         Account details and notifications
		        </a>
		      </h4>
		    </div>
		    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
		      <div class="panel-body">

		      	<h2>Password</h2>
		      	<%= simple_form_for :account, { url: manage_account_path } do |f| %>
				  <%= f.hidden_field :reset_password_token %>
				  <div class="field">
				    <%= f.label :password, "New password" %><br />
				    <% if @minimum_password_length %>
				      <em>(<%= @minimum_password_length %> characters minimum)</em><br />
				    <% end %>
				    <%= f.password_field :password, autofocus: true, autocomplete: "off", :class=>"form-control" %>
				  </div>

				  <div class="field">
				    <%= f.label :password_confirmation, "Confirm new password" %><br />
				    <%= f.password_field :password_confirmation, autocomplete: "off", :class=>"form-control" %>
				  </div>

				  <div class="actions text-center", style="margin-top:10px;">
				    <%= f.submit "Change my password", :class=>"btn btn-primary" %>
				  </div>
				<% end %>

				<%= simple_form_for :notifications, { url: manage_notifications_path } do |f| %>
					<h2>Notifications</h2>
					<p>
						We usually notify you weekly by e-mail with reports. Here you can choose wether
						to recieve or not those reports and which address should we send them.
					</p>

					<p>
						<label>Recieve reports?</label>
					</p>

					<p>
						<%=  f.collection_radio_buttons :recieve_reports, [[true, 'Yes'] ,[false, 'No']], :first, :last%>
					</p>


					<p>
						<label>E-mail address to recieve reports</label>
					</p>

					<p>
  						<%= f.input :email, :label=> false, :class=>"form-control", :placeholder=> @user.email%>
  					</p>

  					<p class="text-center">
  						<%= f.button :submit, "Update", :class=>"btn btn-primary" %>
  					</p>
  					
				<% end %>


		      </div>
		    </div>
		  </div>
		</div>
	</div>
</div>

comigo/app/views/panel/help.html.erb
<div class="row" style="margin-top:30px;">
	
	<div class="col-md-2 well" style="margin-top:30px;">
		<%= render "menu"%>
	</div>	
	
	<div class="col-md-10" style="margin-top:30px;">
		<h1>
			Welcome to dashboard
		</h1>
	</div>
</div>

comigo/app/views/panel/index.html.erb
<div class="row" style="margin-top:30px;">
	
	<div class="col-md-2 well" style="margin-top:30px;">
		<%= render "menu"%>
	</div>	
	
	<div class="col-md-10" style="margin-top:30px;">
		<h1>Welcome to panel</h1>
		<p>
			Here you can manage your products, get billing information
			and set your account. If you face some issue, please contact
			us, we will be happy to help you
		</p>
	</div>
</div>

comigo/app/views/panel/manageproducts.html.erb
<div class="row" style="margin-top:30px;">
	
	<div class="col-md-2 well" style="margin-top:30px;">
		<%= render "menu"%>
	</div>	
	
	<div class="col-md-10" style="margin-top:30px;">
       <div class="row">
       	  <div class="page-header">
       	  	<h1>List of products</h1>
       	  </div>

       	  <table class="table table-striped table-hover">
       	  	<theader>
       	  		<th>Name</th>
       	  		<th>Description</th>
       	  	</theader>

       	  	<tbody>
       	  		<tr>
       	  		  <td>
       	  		  	Cosmo
       	  		  </td>

       	  		  <td>
       	  		  	Social metrics for big pages
       	  		  </td>

       	  		</tr>
       	  	</tbody>
       	  
       	  </table>

       </div>


	   <div class="row">
		   <div class="page-header">	
			<h1>
				Manage products
			</h1>
		   </div>

		   <div class="lead">
		   	 Add a product to an existing user
		   </div>

		   <div class="row">
		   	   <div class="col-md-3"></div>
		   	   <div class="col-md-6 well">
			   <%= simple_form_for :manageproduct, { url: add_product_to_user_path } do |f| %>
				  
				  <p>
				  	<label>User E-mail</label>
				  </p>

				  <p>
				  <%= f.input :user_email, collection: @user_emails, :as => :select, :label => false, :include_blank => false %>
				  </p>
				  
				   <p>
				  	<label>Product Name</label>
				  </p>

				  <p>
				  <%= f.input :product_name, collection: @products, :as => :select, :label => false, :include_blank => false %>
				  </p>

				  <p class="text-center">
				  	Make sure to only click on Add button if the user paid the initial
				  	bill.
				  </p>

				  <div class="text-center">
				  	<%= f.button :submit, "Add", :class=>"btn btn-primary" %>
				  </div>
				<% end %>
				</div>
				<div class="col-md-3"></div>
			</div>
		</div>

	</div>
</div>

comigo/app/views/panel/manageusers.html.erb
<div class="row" style="margin-top:30px;">
	
	<div class="col-md-2 well" style="margin-top:30px;">
		<%= render "menu"%>
	</div>	
	
	<div class="col-md-10" style="margin-top:30px;">
	   <div class="page-header">	
		<h1>
			Manage Users
		</h1>
	   </div>

	   <div class="lead">
	   	 All users
	   </div>

	   <table class="table table-striped table-hover">
	   		<thead>
	   			<th>Fullname</th>
	   			<th>Nickname</th>
	   			<th>E-mail</th>
	   			<th>Products</th>
	   		</thead>

	   		<tbody>
	   			<% for u in @users%>
	   				<tr>
	   					<td><%= u.fullname%></td>
	   					<td><%= u.nickname%></td>
	   					<td><%= u.email%></td>
	   					<td><%= join_products(u.products) %></td>
	   				</tr>

	   			<% end %>
	   		</tbody>
	   </table>

	</div>
</div>

comigo/app/views/panel/trainai.html.erb
<div class="row" style="margin-top:30px;">
	
	<div class="col-md-2 well" style="margin-top:30px;">
		<%= render "menu"%>
	</div>	
	
	<div class="col-md-10" style="margin-top:30px;">
       <div class="page-header">
       	  <h1>Feedback comment's classification</h1>
   	   </div>

   	   <div>

		  <!-- Nav tabs -->
		  <ul class="nav nav-tabs" role="tablist">
		  	<li role="presentation" class="active"><a href="#already-validated" aria-controls="home" role="tab" data-toggle="tab">Already Validated</a></li>
		    <li role="presentation" ><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Facebook</a></li>
		    <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Twitter</a></li>
		  </ul>

		  <!-- Tab panes -->
		  <div class="tab-content">
		  	  <div role="tabpanel" class="tab-pane active" id="already-validated">
			   	   <% if !@human_interactions_validated.blank?%>
			   	   

			   	   <b>Number of already validated comments:</b>
			   	   <%=@human_interactions_validated_count%> 
                   
                   <h1>Numbers</h1>
                   
                   <div class="row">
                   	   <div class="col-md-2"></div>
	                   <div class="col-md-8">
		                   <table class="table table-striped table-hover">
		                   	<thead>
		                   		<th>User</th>
		                   		<th>Number of validated comments</th>
		                   		<th>Number of validated retweets</th>
		                   	</thead>
		                   	<tbody>
		                   		<% for u in @users %>
		                   			<tr>
		                   				<td>
		                   					<b>
		                   						<%= u.nickname%>
		                   					</b>
		                   				</td>

		                   				<td>
		                   					<%= number_of_validated_comments(u.nickname)%> /
		                   					<%= total_number_of_comments(u.nickname) %>
		                   				</td>
		                   				
		                   				<td>
		                   					<%= number_of_validated_retweets(u.nickname)%> / 
		                   					<%= total_number_of_retweets(u.nickname) %>
		                   				</td>

		                   			</tr>
		                   		<% end %>
		                   	</tbody>                        
		                   </table>
	                   </div>
	                   <div class="col-md-2"></div>
	                </div>

                   <h1>List</h1>
			   	   <div class="row">
			   	   	   <div class="col-md-2"></div>
			   	   	   <div class="col-md-8">
					   	   <table class="table table-striped table-hover">
						   	   	<thead>
						   	   		<th>User</th>
						   	   		<th>Text</th>
						   	   		<th>Reaction</th>
						   	   	</thead>
						   	   	
							   	<tbody>
							   	   	<% for h in @human_interactions_validated%>
							   	   		<tr>
							   	   			<td>
							   	   				<b>
							   	   					<%= h.user_nickname%>
							   	   				</b>
							   	   			</td>
							   	   			<td>
							   	   				<%= h.comment_text%>
							   	   			</td>
							   	   			
							   	   			<td>
							   	   				<% if h.reaction_type =="positive"%>
							   	   					<span class="label label-success">
							   	   						<%= h.reaction_type%>
							   	   					</span>
							   	   				<%elsif h.reaction_type =="negative"%>
							   	   					<span class="label label-danger">
							   	   						<%= h.reaction_type%>
							   	   					</span>
							   	   				<% else %>
							   	   					<span class="label label-default">
							   	   						<%= h.reaction_type%>
							   	   					</span>
							   	   				<% end %>
							   	   			</td>
							   	   			
							   	   		</tr>
							   	   	<% end %>
							   	</tbody>
					   	   </table>
				   		</div>
				   	   <div class="col-md-2"></div>
				   	  </div>
			   	   <%else%>
				   	   <div class="row">
					   	   <p>
					   	   	<h1 class="text-center">
					   	   		No validated comments to show yet :(
					   	   	</h1>
					   	   </p>
				   		</div>
			   	   <% end %>

		    </div>


		    <div role="tabpanel" class="tab-pane" id="home">
		    	   <% if !filter_not_validated(@human_interactions_facebook).blank?%>
		    	   	<div class="row text-center">
			    	   	<h4>Fast navigation</h4>
			    	   	<% for u in filter_not_empty_users(@users, "facebook") %>
			    	   		<a href="/panel/trainai/<%= u.nickname%>">
			    	   			<%= u.nickname%>
			    	   		</a>
			    	   	<% end %>
		    	   </div>
		    	    <div class="row">
		    	    	<div class="col-md-2"></div>
			    	    <div class="col-md-8">
				    	    <table class="table table-striped table-hover" style="width:600px; max-width:600px;">
						   	   	<thead>
						   	   		<th>User</th>
						   	   		<th>Text</th>
						   	   		<th>Reaction</th>
						   	   		<th>Options</th>
						   	   	</thead>
						   	   	
							   	<tbody id="fb-tbody">
							   	  <% for h in filter_not_validated(@human_interactions_facebook)%>
					   	       		<%= render :partial => "humaninteractionfacebook", locals: {:h => @human_interactions.find(h._id)} %>
					   	   		  <% end %>
					   	   		</tbody>
					   	   	</table>
				   	   </div>
				   	   	<div class="col-md-2"></div>
			   	    </div>

			   	   <% else %>
			   	   		<div class="row">
				   	   		<p>
					   	   	<h1 class="text-center">
					   	   		No facebook comments to show yet :(
					   	   	</h1>
					   	   </p>
				   	   </div>
			   	   <% end %>
		    </div>
		    <div role="tabpanel" class="tab-pane" id="profile">
		    	 <% if !filter_not_validated(@human_interactions_twitter).blank?%>
			   	    
			   	   	<div class="row text-center">
			    	   	<h4>Fast navigation</h4>
			    	   	<% for u in filter_not_empty_users(@users, "twitter") %>
			    	   		<a href="/panel/trainai/<%= u.nickname%>">
			    	   			<%= u.nickname%>
			    	   		</a>
			    	   	<% end %>
		    	   </div>
		    	    <div class="row">
		    	    	<div class="col-md-2"></div>
		    	    	<div class="col-md-8">
					   	    <table class="table table-striped table-hover">
						   	   	<thead>
						   	   		<th>User</th>
						   	   		<th>Text</th>
						   	   		<th>Reaction</th>
						   	   		<th>Options</th>
						   	   	</thead>
						   	   	
							   	<tbody id="tw-tbody">
					   	    		<% for h in filter_not_validated(@human_interactions_twitter)%>
					   	    			<%= render :partial => "humaninteractiontwitter", locals: {:h => @human_interactions.find(h._id)} %>
					   	    		<% end %>
		                    	</tbody>
		                    </table>
	                	</div>
	                    <div class="col-md-2"></div>

                	</div>

			   	   <% else%>
			   	  	  <div class="row">
			   	  		<p>
				   	   	<h1 class="text-center">
				   	   		No tweets to show yet :(
				   	   	</h1>
				   	   </p>
				   	</div>
			   	   <% end %>
		    </div>

		  </div>

		</div>



	</div>
</div>