comigo/config/routes.rb
Rails.application.routes.draw do
  get 'monitor/index'

  get 'dashboard/index'

  get 'dashboard/account'

  get 'dashboard/billing'

  get 'dashboard/help'

  get 'dashboard/myproducts'

  get 'cosmo/index'

  get 'panel/index'

  get 'home/index', :as=> :home_index
  
  get 'home/pricing'

  get 'home/about'

  get 'home/contact'

  get "home/privacy_policy"
  
  get "panel/manageusers"
  get "panel/manageproducts", :as => :dashboard_manage_products
  get "panel/account", :as => :dashboard_manage_account
  get "panel/billing"
  get "panel/help"
  
  get "panel/trainai/:nickname", to: "panel#trainai"
  get '/panel/trainai', to: redirect('/panel/trainai/all')

  get '/panel',  to: 'panel#index'
  get "/dashboard", to: "dashboard#index"
  
  get "/cosmo", to: "cosmo#index"
  get "cosmo/facebook"
  get "cosmo/twitter"
  get "cosmo/instagram"
  

  root 'home#index'
  
  post "panel/add_product_to_user", :as => :add_product_to_user
  
 

  post "panel/manage_notifications", :as => :manage_notifications

  get "human_interactions/destroy/:id" => "human_interactions#destroy", :as => :destroy_interaction
  post "human_interactions/update/:id" => "human_interactions#update", :as => :update_interaction

  devise_for :user, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations',
    omniauth_callbacks: "omniauth_callbacks"
  }
  
  resource :user

  devise_scope :user do
    get '/login', to: 'user/sessions#new'
  end
  
  devise_scope :user do
    get '/signup', to: 'user/registrations#new'
  end

  devise_scope :user do
    get "/logout" => "user/sessions#destroy", :as => :quit_session
  end

  devise_scope :user do
    post "/user/create" => "user/registrations#create", :as=> :create_user_path
  end

  devise_scope :user do
    post "/user/update_profile" => "user/registrations#update_profile", :as=> :manage_user_profile
  end

  devise_scope :user do
     post "/user/update_social_accounts" => "user/registrations#manage_sn_accounts" , :as => :manage_sn_accounts
  end

  devise_scope :user do
    post "/user/password/update" => "user/passwords#update", :as=> :manage_account
  end

  get "/panel/manageusers", :as => :dashboard_manage_users
  

end

comigo/app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-warning">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <p class="text-center" style="font-weight:bold;">
      	<%= value %>
  	  </p>
  </div>
<% end %>

comigo/app/views/layouts/cosmo.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Comigo" %></title>
    <%= csrf_meta_tags %>
    <link rel="icon" href="icon.png">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
   <%= javascript_include_tag :defaults %>
   <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
   <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
   <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
   
    <%= stylesheet_link_tag "cosmo", :media => "all" %>

    <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>
    <script src='https://www.google.com/jsapi'></script>
  </head>
  <body>
    
  <div class="row">
      <%= render "layouts/messages" %>
      <%= yield %>
  </div>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        
        <a class="navbar-brand" href="/home/index">
              <span style="font-size:35px;">
                Comigo<b>!</b>
              </span> 
              
        </a>
        
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        
        <% if controller_name == "home"%>
          <ul class="nav navbar-nav">
            <li class="active">
              <li class="active"><a href="/home/index">Home</a></li>
              <li><a href="/home/pricing">Pricing</a></li>
              <li><a href="/home/about">About</a></li>
              <li><a href="/home/contact">Contact</a></li>
            </li>
          </ul>
        <%end%>

        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            
            <% if user_signed_in?%>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
             
             <% if current_user.is_admin == true%>
                  <%= current_user.fullname %> 
                  <span class="label label-success">Admin</span>
             <% else %>
                 <%= current_user.fullname %>
             <% end %>

            <span class="caret"></span></a>

            <% else %>
             <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Not logged in<span class="caret"></span></a>
            <% end %>
            <ul class="dropdown-menu">
                <% if user_signed_in?%>
                  
                  <% if current_user.is_admin == false %>
                    <li>
                      <a href="/dashboard/index">Dashboard</a>
                    </li>
                    <li>
                      <a href="/dashboard/account">Account</a>
                    </li>
                  <% else %>
                   <li>
                      <a href="/panel/index">Panel</a>
                    </li>
                    <li>
                      <a href="/panel/account">Account</a>
                    </li>
                  <% end %>

                  <li>
                   <%= link_to "Log out", quit_session_path %>
                  </li>

                  <% if !current_user.products.blank?%>
                    <li role="separator" class="divider"></li>
                    <% for p in current_user.products%>   
                      <li>
                        <a href="/<%=p.downcase%>/index">
                          <%= p.capitalize %>
                        </a>  
                      </li>

                    <% end %>

                  <%end%>

                <%else%>
                  <li><a href="/login">Login</a></li>
                  <li><a href="/signup">Create an account</a></li>
              <% end%>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  
    <footer>
      <p class="text-center">
        &copy;Comigo!- All rights reserved
      </p>

      <p class="text-center">
        <a href="/home/privacy_policy">Privacy policy</a>
      </p>

    </footer>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "cosmo" %>

    <%= yield(:page_javascript) if content_for?(:page_javascript) %>
  </body>
</html>